services:
  - type: web
    name: lancasterwx-radar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python process-radar.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
